### ISSUE TITLE
Reset tacking vote when a waypoint is reached

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#105]
Right now after reaching a waypoint the boat will wait some times (7.5s currently) before going in the direction of the new waypoint.

**Comment by smaria** [comment]
The question is how much time we want to spend on the tacking vote, considering that really this is not our final strategy

**Comment by Nanoseb** [comment]
I think this can be our final strategy, and to improve it we can just change the pool time depending on the distance to waypoint (longer when we are further from the waypoint).

**Comment by smaria** [comment]
We now only use the tack vote when we get close to a waypoint.
