### ISSUE TITLE
Jibe when necessary

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#106]
The boat is only doing tacks when it wants to change tack even if sometimes a jibe is more appropriate.

**Comment by takluyver** [comment]
See also #31 - because we don't currently track where the sail is, we may jibe unexpectedly when going downwind. It's not clear whether this is a problem with no human sailors to be hit by the boom.

**Comment by Nanoseb** [comment]
We don't really care about where the sail is and unexpected jibing here I think. Unlike a tack, you can jibe when ever you want and you will not loose speed.

If we want to improve performances of the boat we should avoid going between ~165 and ~195, and implement a 'jibing' strategy similar to the tacking one though.

**Comment by Nanoseb** [comment]
![160713--1468412585](https://cloud.githubusercontent.com/assets/10603482/16803279/cf4817b8-4905-11e6-81c8-27a9cf7f495a.png)
(wind from the south and the boat is going north)

**Comment by Nanoseb** [comment]
Just realised that the area scanning challenge will include only jibe, so it will save quite some time if the boat can actually jibe.

**Comment by Nanoseb** [comment]
When the waypoint in downwind we can just go in straight line without taking care of the wind direction and the jibe, that is the easiest solution, and it will work quite well I think.

**Comment by Nanoseb** [comment]
This is a fix that is working, the boat jibe when expected, @takluyver I let you improve it, maybe you want to keep updating the tackvoting when going downwind, or reset it (?).

**Comment by takluyver** [comment]
I've just added a parameter that we can switch it to jibing rather than tacking if conditions make that seem more favourable. Between that and @Nanoseb's fixes, I think we can close this.
