### ISSUE TITLE
Should magnetic field readings be divided by scale?

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#119]
The compass calibration script [records the 'scale' parameters](https://github.com/Maritime-Robotics-Student-Society/sailing-robot/blob/40882029dc15f1f768509693585a3145dd052eed/utilities/calibration_scripts/compasscalib#L171-L173) as the range of the readings, i.e. `max - min`. Then the sensor driver script [multiplies by the scale](https://github.com/Maritime-Robotics-Student-Society/sailing-robot/blob/40882029dc15f1f768509693585a3145dd052eed/src/sailing_robot/scripts/sensor_driver_imu#L159-L161). Maybe I'm confused, but I think we should be dividing by the range to normalise it, not multiplying.

In principle, I think the range should be the same in all dimensions, so it shouldn't matter too much. I noticed it when I published the normalised field readings for debugging, and they're such huge numbers that it's hard to compare them in the dashboard.

**Comment by Nanoseb** [comment]
Oh yes you are right I think, probably a miss understanding when we did that code (I was doing the calibration when Sophia was writing the node). I think you can safely change that.
