### ISSUE TITLE
Can't tack in moderate waves

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#120]
We tested today at the upper end of the wind speeds we may have to sail in, and there were small waves (maybe 10-20cm). We discovered that it was almost impossible to tack in these conditions, even with manual control - the boat being very light, it has little momentum, and as soon as it tries to turn into the wind, it loses speed.

We were still able to jibe, so we should probably include an option to jibe rather than trying to tack for these conditions.

The boat was also not able to sail very close to the wind, so we would have had a very hard time going upwind.

**Comment by pierbiag** [comment]
All these problems related to overhealing and maneuverability in strong winds will ideally be solved by the smaller set of sails we are purchasing 

Pier Maria Biagiolini

**Comment by takluyver** [comment]
Great. Do we know when they'll arrive?

**Comment by pierbiag** [comment]
I'm waiting a reply from the guy at sails etc so we can confirm the purchase

**Comment by smaria** [comment]
Sails are here. However, jibing is still something we need to teach our boat to do.

**Comment by smaria** [comment]
#106 deals with jibing. it may be worth adding to jibe when tacking hasn't worked a couple of times at a later time.

**Comment by takluyver** [comment]
Closing this as we have both smaller sails and code for jibing. If we're tagging issues 'wontfix', we should probably close them.
