### ISSUE TITLE
make spare wind sensor

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#128]
this involves:
- 3d print another base
- glue magnets to wind vane
- cut metal rod of spare wind vane

**Comment by takluyver** [comment]
We had a spare wind vane in Viana, but I don't think it was wired/magnet-ed up to be ready to switch in as a sensor.

**Comment by tsaoyu** [comment]
We have run out of magnet and magnetometer for spare. 
Parts will be ordered once we got new sub project code.
