### ISSUE TITLE
write basic heading_control node

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#13]
write node to make decision on goal heading and tacking/no tacking state

**Comment by UnnamedMoose** [comment]
Chapter 4 from this is very relevant.

[PhD - Scarponi M 2007.pdf](https://github.com/Maritime-Robotics-Student-Society/sailing-robot/files/117113/PhD.-.Scarponi.M.2007.pdf)

**Comment by takluyver** [comment]
This is in place, though no doubt there will be improvements to make.
