### ISSUE TITLE
Sort and pack tools

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#130]
We need a clear list of tools that we are taking to the competition. I started a list in notes (not as originally stated here: utilities).

**Comment by smaria** [comment]
wiki would be a nicer place for this, but git is nicer for editing at any time (yes, the wiki is also a git, but we don't have clones of that everywhere ;)

**Comment by takluyver** [comment]
It's not a bad idea to have clones of the wiki handy for offline reference, though; I have it on my laptop.

**Comment by Nanoseb** [comment]
And a printed version as well.

**Comment by smaria** [comment]
good point, created #132
