### ISSUE TITLE
Always jibe parameter is not working properly

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#137]
I have tested the parameter `jibe_to_turn` in the simulator, in this case it worked once but on the second jibe it starts making 360° and after 3-4 of them the boat goes in the exact opposite direction to the waypoint.

And sometime it is even without making 360° but the boat directly goes in the opposite direction.

**Comment by Nanoseb** [comment]
Some more info, when the boat goes away from the waypoint its sailing_state is `normal` and during 360° it is `jibe_to_port_tack` the entire time.

Here the boat starts to make loops, the wind is coming from the north and the waypoint is the one on the top right.
![160902--1472836847](https://cloud.githubusercontent.com/assets/10603482/18212663/b0562f7c-7144-11e6-94a6-4c94164d2975.png)

Wind conditions are the same, and the boat didn't make any 360 here.
![160902--1472837187](https://cloud.githubusercontent.com/assets/10603482/18212656/a9334180-7144-11e6-8b28-f46123b1481b.png)

Also sometimes the boat also just keeps making 360.

**Comment by Nanoseb** [comment]
I have tried some things but same result...

Anyway I have tried my 'force_jibe' node that is making the boat jibe when a tack is failing (= take too much time), and this one is working well so maybe the always jibe is not entirely needed.

**Comment by takluyver** [comment]
I've tracked down the going round in circles issue - I'd missed out the `el` of an `elif`. I'm less sure about what makes it head off in the wrong direction.

@Nanoseb rviz doesn't work on my ROS VM (it segfaults) - do you have time to test this again, since you can see better than me what's going on?

**Comment by Nanoseb** [comment]
Yes, I can test this right now.

**Comment by takluyver** [comment]
Thanks! :smiley:

**Comment by Nanoseb** [comment]
Ok it seems to work correctly now!

**Comment by takluyver** [comment]
Excellent. Those two characters make all the difference :-)

**Comment by Nanoseb** [comment]
Can you make it so that it will try to jibe only when a certain topic is published ? (so we can detect if a tack is failing)

**Comment by takluyver** [comment]
I'm not exactly sure what you're thinking. I'm trying to work on #51 now, so if you can see what you need to do, go for it.
