### ISSUE TITLE
X86 micro-controller?

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/sailing-robot#144]
https://software.intel.com/en-us/iot/hardware/joule

Key-features:
- 64bit X86 arch 
- ROS compatible
- 48GPIO with 4 hardware PWM 
- MHF4 connectors for external antennae
- on chip Intel HD graphics card

**Comment by takluyver** [comment]
Jealous of the boat running Windows? ;-)

I don't think we ran into any limits of computational power or connectivity, so I'd be inclined to stick with the Raspi - they're cheap, readily available, and there's a lot of information already out there from people who've already done all kinds of things with them. The most attractive thing on the feature list is the connections for antennae, but I don't know if we'd actually use that.

**Comment by tsaoyu** [comment]
Haha, I am really Jealous on their Windows 10 computer stick.

The most attractive part for me is X86 arch with Ubuntu Core. 
It opens greater possibility for more ROS libraries. 
For example, sensor fusion library with http://wiki.ros.org/robot_localization 

It also have drawback like smaller user community and higher price.

**Comment by takluyver** [comment]
I'm confused - does that library require x86? Or does it need more processing power than we have?

**Comment by Nanoseb** [comment]
The processing power is really not an issue atm, when every thing is launched we use about 10-20% of the total cpu, even the opencv lib did not use much cpu

**Comment by tsaoyu** [comment]
No, this library requires dependencies which is not available on ARM.

**Comment by takluyver** [comment]
Which deps are those? Searches aren't turning up much info.

**Comment by tsaoyu** [comment]
Don't remember atm, I  will let you know once I meet Brain

 ![BRIAN](http://orig13.deviantart.net/9e86/f/2009/264/2/a/brian_griffin__by_gloohmy.gif)

**Comment by takluyver** [comment]
Closing for now as we have no current plans to move to x86. We'll keep our eyes open for different options, though.
