### ISSUE TITLE
Investigate mosh as an alternative to ssh

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#153]
MOSH should have many nice advantages especially on bad wifi connections
https://mosh.org/

**Comment by Nanoseb** [comment]
This seems really interesting, and there is nothing to install/setup on the pi.

**Comment by tsaoyu** [comment]
Both side need installation though. But configuration is fairly simple if the package is ready. 
------------------ Original ------------------

**Comment by takluyver** [comment]
It should be as simple as `apt-get install mosh`. Hopefully the versions on the client and the server don't need to match too closely.

**Comment by tsaoyu** [comment]
`mosh` has been installed and tested on RPi
