### ISSUE TITLE
Define calibration procedure

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#17]
Which parts need calibration when the boat is (re-) assembled?
Since we need to bring the boat to testplaces, we need a clear list what scripts we need to run e.g. to recalibrate the compass

**Comment by tsaoyu** [comment]
Compass do need calibration but that is an one-off task at this moment.
@Nanoseb and I have found some calibration tool for the magnetometer. 
We will work on the calibration part of sensor once we finished the wind vane assembly.
