### ISSUE TITLE
Indexing tool for rosbags

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#176]
I'd like to write a tool that can index rosbags, so I can quickly see details like how long each one was recorded for and which topics it contains.

**Comment by Nanoseb** [comment]
That is really nice!
Small improvement: right now the oldest date is first when the reverse is more useful

**Comment by takluyver** [comment]
Thanks! I've reversed the sort order so the newest ones appear at the top.

**Comment by smaria** [comment]
https://github.com/ewerlopes/rosbag-sliding-windows-annotator
not a finished thing, but they seem to be trying to do a similar thing to us

**Comment by takluyver** [comment]
There's some similarity, but I think it's different from what I'm trying to do. I can't quite get from the description what sort of thing that would be used for, but they seem to be talking about annotating data inside a rosbag using images also stored in the rosbag. This tool is to give us an overview of our different rosbag files.

**Comment by takluyver** [comment]
This is now there and working nicely:
https://github.com/Maritime-Robotics-Student-Society/sailing-robot/blob/master/utilities/index_recorded_data.py

Result:

![screenshot from 2017-07-03 21-28-18](https://user-images.githubusercontent.com/327925/27807109-a00d44b6-6036-11e7-9004-1aceb398775b.png)

The remaining change that I want to make is to add jinja2 to our docker image, because currently I have to launch docker and install it each time I want to use it.

**Comment by takluyver** [comment]
OK, now if you don't have ROS, but do have docker, you can run the indexing script in a docker container like this:

```

**Comment by takluyver** [comment]
OK, now if you don't have ROS, but do have docker, you can run the indexing script in a docker container like this:

```
./utilities/index_recorded_data.py --docker
```
