### ISSUE TITLE
Additional wiring for autonomous mode feedback

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/sailing-robot#179]

**Comment by alvaropp** [comment]
![8abcfe7ed646cbc06739b12d577893bb](https://cloud.githubusercontent.com/assets/4785303/22947335/88788d62-f2f2-11e6-89f5-b904ce63397e.png)

**Comment by alvaropp** [comment]
![](http://i65.tinypic.com/2qasg7r.png)
