### ISSUE TITLE
Check servo wiring issue

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/sailing-robot#182]
We found rudder servo do not work properly in autonomous mode, maybe it is worthwhile to use logic analyser to check what happen to rudder servo control.

**Comment by takluyver** [comment]
We think this is probably a bad connection at the RPI gpio pins.

**Comment by smaria** [comment]
Interesting, especially combined with the weird IMU issues we had. Maybe its time to move on from the free flying wiring?

**Comment by alvaropp** [comment]
28/02/17 conclusion: the rudder servo pin connection seems a bit dodgy. We got weird PWM readings once when shaking the RPi, which we couldn't replicate later on.

**Comment by alvaropp** [comment]
Changed the wire and _seems_ fine now
