### ISSUE TITLE
Run tests from continuous integration

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#19]
We have CI on Travis, but it currently just checks that everything builds. Add the ability to run tests which will be separately created.

**Comment by smaria** [comment]
maybe we can use the outcomes of roswtf in this

**Comment by takluyver** [comment]
We're now running nosetests on Travis. At some point we'll probably want to run tests with rostest as well, so leaving this open for now.

**Comment by takluyver** [comment]
Now we have the framework in place for rostests as well, and the tests run on Travis.
