### ISSUE TITLE
Test camera calibration

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#195]
I reprogrammed the calibration procedure for the camera color detection. But since I won't be the one using it, some of you need to try it and tell me if it is understandable.
(Ros is not needed to run the calibration)

``` /sailing-robot/utilities/calibration_scripts/camera_detection_calibration.py ```

**Comment by takluyver** [comment]
Sophia did it, it seemed to work nicely. :-)
