### ISSUE TITLE
Figure out how to calibrate Xsens without connecting to a laptop

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#198]
To calibrate the Xsens, we currently have to unplug it from the raspi and plug it in to a laptop using USB to run the magnetic field manager GUI. We've only got this program compiled for x86/x64, so we can't run it directly on the pi. However, it can run on a data file collected separately, rather than reading the Xsens live.

- [ ] Record the necessary data format using the raspi
- [ ] Write the generated calibration model to the Xsens from the raspi
- [ ] Automate moving the data between a raspi and a laptop (optional)

Another option would be to connect to the raspi and use its USB port remotely - I don't know if this is possible or how we would do it.

**Comment by tsaoyu** [comment]
The "another" option seems pretty neat to me. I found something claim to do this https://virtualhere.com/home

**Comment by takluyver** [comment]
Aha, and that appears to be based on a Linux feature called usbip. I think we can probably figure out how to use that directly, rather than using a proprietary wrapper.

**Comment by Nanoseb** [comment]
this looks super straight forward: https://www.howtoforge.com/how-to-set-up-a-usb-over-ip-server-and-client-with-ubuntu-10.04
usbip is probably in the repo for ubuntu.

**Comment by takluyver** [comment]
I've been trying to set this up, but run into problems with the fact that all the packages on the raspi are out of date - I can't install new packages compatible with the old ones on there. @tsaoyu can you remember what the problem was with updating before? Can I try updating everything and see what breaks?

**Comment by Nanoseb** [comment]
just tried between 2 up to date archlinux, and I can't make it work, I have an error at the very end (during the attach). It isn't as straight forward as I thought ;)

**Comment by Nanoseb** [comment]
Done, thx @takluyver  !
d68b23b
