### ISSUE TITLE
Scale Image Widths To Fit Parent Anchor Width In Blog

### ISSUE THREAD

**Issue by ZhongYuenLee** [Maritime-Robotics-Student-Society/sailing-robot#206]
In the blog, the images aren't necessarily the same width as its parent anchors. This results in an ugly grey background to the right of the image when the user hovers over it. So yeah, fix it.

**Comment by ZhongYuenLee** [comment]
Don't tell me what to do

**Comment by ZhongYuenLee** [comment]
[Dunnit](https://github.com/Maritime-Robotics-Student-Society/blog/commit/172a8c86c4bcfe9a5fd1f949cf92df0e7166dc6b). Also should've opened this issue in the blog repo instead of this one.

**Comment by takluyver** [comment]
Can confirm, no more grey margin. Thanks!
