### ISSUE TITLE
Document High level task system

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#208]
RIght now there is no documentation on the task system except comments. Having a Wiki section that describes the philosophy behind it and maybe an overall explanation of each component will be useful for new comers (and even for me ;) ).

I can start writing the things I understand, but @takluyver I think you will be needed ;)

**Comment by takluyver** [comment]
Pretty sure I already wrote something on the wiki to describe the main
concepts.

**Comment by Nanoseb** [comment]
Oh yes, that's true, my bad, I'll look more carefully into that.
Closing this issue, I'll reopen more specific ones if needed
