### ISSUE TITLE
Add map to index_recorded_data

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#227]
A .kmz can be read by almost any maps like openstreet map/google earth/map etc. It could be a nice addition to the index_recorded_data.py script to have an osm map summarizing the bagfile.

Such file can be easily generated from the .csv we already record with pyKML for example (no need to parse the huge bagfile or generate this live).

**Comment by Nanoseb** [comment]
http://osm.quelltextlich.at/wizard-kml-osmtools.html for example to generate easily the map afterwards

**Comment by takluyver** [comment]
The [folium](http://folium.readthedocs.io/en/latest/) library can plot over Openstreetmap directly, without needing to make a kml file. I used this last year to plot the tracks from the competition:

http://nbviewer.jupyter.org/github/Maritime-Robotics-Student-Society/sailing-robot/blob/master/notes/WRSC%202017%20results.ipynb

**Comment by Nanoseb** [comment]
Oh yes nice, I didn't realised you got an actual osm thing. So it may be even easier to add to the index page. 
Definitely worth looking at then.

**Comment by Nanoseb** [comment]
Basic version working \o/, still needs waypoints now
![scrot-2018-02-08-151918](https://user-images.githubusercontent.com/10603482/35980856-b0dc15e2-0ce3-11e8-843f-580a2b629a4f.png)

**Comment by takluyver** [comment]
Nice! It should be easy to get the waypoints from the parameter dump.

**Comment by Nanoseb** [comment]
yes, it is just not a copy/paste from your code since it is json vs yaml ;). But yes shouldn't be complicated

**Comment by Nanoseb** [comment]
@takluyver can you test with all the bags/.csv? 
If there is no loading issue and it works fine I think we can close this.

**Comment by takluyver** [comment]
We are going to need to be smarter with the loading, unfortunately. When I generated the index with all the maps, it took over a minute to load in my browser and made 1500 requests. I'll see if I can figure something out.

**Comment by takluyver** [comment]
OK, now it only loads the map when you click the link to open it for the first time.
