### ISSUE TITLE
Position estimate

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#23]
A position estimate needs to be generated from GPS and IMU
> does this use speed estimates from the (to be done) speed_estimate #21  node or does it use IMU values directly?
> there is a ros node for generating a position from GPS and IMU, which is it, is it suitable?

**Comment by tsaoyu** [comment]
This problem is related to #86 #21.

**Comment by smaria** [comment]
our gps is accurate enough at the top of the mast.
