### ISSUE TITLE
Installation: testresources, tornado, setup.py

### ISSUE THREAD

**Issue by bryzhao** [Maritime-Robotics-Student-Society/sailing-robot#234]
Hi Soton team,

During the installation step on the sailing-robot wiki (https://github.com/Maritime-Robotics-Student-Society/sailing-robot/wiki/Virtual-Machine-for-Windows-Mac-users), under the **Post installation setup** section, where the instructions say:

- Install the needed dependencies for the sailing robot

`~/sailing-robot/utilities/setup_scripts/Install_needed_packages.sh`

I get the following errors in my terminal (in bold):
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bc is already the newest version.
gpsd-clients is already the newest version.
i2c-tools is already the newest version.
libgeos-dev is already the newest version.
python-scipy is already the newest version.
vim is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 296 not upgraded.
Installing Python packages...
The directory '/home/bryanz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bryanz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (10.0.1)
**launchpadlib 1.10.2 requires testresources, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.**
The directory '/home/bryanz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bryanz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Latlon
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/cf/f0/5c23d9431a69cf27d139e9ae09db7f0f032c88192384dad3f8d7e0c860e8/LatLon-1.0.2-py2-none-any.whl
Collecting shapely
  Downloading https://files.pythonhosted.org/packages/a5/cf/0d51a15861d944da8463d8c1aecf39cfc6852ea9ecd092046824e9b237b3/Shapely-1.6.4.post1-cp27-cp27mu-manylinux1_x86_64.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 6.7MB/s 
Collecting pyproj
  Downloading https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 1.6MB/s 
Collecting pynmea2
  Downloading https://files.pythonhosted.org/packages/7c/82/f734e75dbb0aecbd9ea20489f364fdac9f124f17c4d4e26d2ab160c8ff58/pynmea2-1.12.0.tar.gz
Collecting spidev
  Downloading https://files.pythonhosted.org/packages/36/83/73748b6e1819b57d8e1df8090200195cdae33aaa22a49a91ded16785eedd/spidev-3.2.tar.gz
Collecting tornado
  Downloading https://files.pythonhosted.org/packages/cf/d1/3be271ae5eba9fb59df63c9891fdc7d8044b999e8ac145994cdbfd2ae66a/tornado-5.0.2.tar.gz (506kB)
    100% |████████████████████████████████| 512kB 9.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-IuomJA/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-IuomJA/tornado/**

So far, I have tried `pip install --user launchpadlib==1.10.2`, as well as updating to Python 3.6.x, and then re-running the installation instruction, but I still get the same errors.

Any help would be much appreciated. Thank you!

**Comment by Nanoseb** [comment]
I have seen you have tried the docker image too, I would recommend using that instead of virtual box, it is easier to set up, specially to have a share folder between your computer and the virtual environment.

**Comment by bryzhao** [comment]
@takluyver @Nanoseb thanks for the reply. I used `pip install launchpadlib == 1.10.2 --user` to install testresources, and `pip install tornado==4.1 --user` to install a tornado version (older than 5). Changing the bash script to `pip install "tornado<5"` unfortunately did not work for me. 

Additionally, I encountered two more errors after running the installation script - in which the packages pigpio and python-pigpio are not located (in bold at the bottom):

Reading package lists... Done
Building dependency tree       
Reading state information... Done
bc is already the newest version.
gpsd-clients is already the newest version.
i2c-tools is already the newest version.
libgeos-dev is already the newest version.
python-scipy is already the newest version.
vim is already the newest version.
python-pip is already the newest version.
The following packages were automatically installed and are no longer required:
  cmake cmake-data collada-dom-dev collada-dom2.4-dp-base
  collada-dom2.4-dp-dev freeglut3 gir1.2-gtk-2.0 hddtemp icu-devtools
  liballegro4.4 liballegro4.4-plugin-alsa libapr1-dev libaprutil1-dev
  libassimp-dev libassimp3 libatk1.0-dev libavcodec-dev libavformat-dev
  libavutil-dev libboost-all-dev libboost-atomic-dev libboost-atomic1.54-dev
  libboost-atomic1.54.0 libboost-chrono-dev libboost-chrono1.54-dev
  libboost-chrono1.54.0 libboost-context-dev libboost-context1.54-dev
  libboost-context1.54.0 libboost-coroutine-dev libboost-coroutine1.54-dev
  libboost-date-time-dev libboost-date-time1.54-dev libboost-dev
  libboost-exception-dev libboost-exception1.54-dev libboost-filesystem-dev
  libboost-filesystem1.54-dev libboost-filesystem1.54.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-graph-parallel1.54-dev
  libboost-graph-parallel1.54.0 libboost-graph1.54-dev libboost-graph1.54.0
  libboost-iostreams-dev libboost-iostreams1.54-dev libboost-iostreams1.54.0
  libboost-locale-dev libboost-locale1.54-dev libboost-locale1.54.0
  libboost-log-dev libboost-log1.54-dev libboost-log1.54.0 libboost-math-dev
  libboost-math1.54-dev libboost-math1.54.0 libboost-mpi-dev
  libboost-mpi-python-dev libboost-mpi-python1.54-dev
  libboost-mpi-python1.54.0 libboost-mpi1.54-dev libboost-mpi1.54.0
  libboost-program-options-dev libboost-program-options1.54-dev
  libboost-program-options1.54.0 libboost-python-dev libboost-python1.54-dev
  libboost-python1.54.0 libboost-random-dev libboost-random1.54-dev
  libboost-random1.54.0 libboost-regex-dev libboost-regex1.54-dev
  libboost-regex1.54.0 libboost-serialization-dev
  libboost-serialization1.54-dev libboost-serialization1.54.0
  libboost-signals-dev libboost-signals1.54-dev libboost-signals1.54.0
  libboost-system-dev libboost-system1.54-dev libboost-test-dev
  libboost-test1.54-dev libboost-test1.54.0 libboost-thread-dev
  libboost-thread1.54-dev libboost-thread1.54.0 libboost-timer-dev
  libboost-timer1.54-dev libboost-timer1.54.0 libboost-tools-dev
  libboost-wave-dev libboost-wave1.54-dev libboost-wave1.54.0 libboost1.54-dev
  libboost1.54-tools-dev libcairo-script-interpreter2 libcairo2-dev
  libcegui-mk2-0.7.6 libcf0 libconsole-bridge-dev libconsole-bridge0.2 libcr0
  libcurl4-openssl-dev libcv-dev libcvaux-dev libdc1394-22-dev libdevil-dev
  libdevil1c2 libeigen3-dev libflann-dev libflann1.8 libfltk1.1 libfltk1.1-dev
  libfreeimage-dev libfreeimage3 libgcrypt11-dev libgdk-pixbuf2.0-dev
  libgl2ps-dev libgl2ps0 libglib2.0-dev libgnomecanvas2-0
  libgnomecanvas2-common libgnutls-dev libgnutlsxx27 libgpg-error-dev
  libgsl0ldbl libgtest-dev libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
  libhdf5-7 libhighgui-dev libhwloc-dev libhwloc-plugins libhwloc5
  libibverbs-dev libibverbs1 libicu-dev libidn11-dev libilmbase-dev
  libjasper-dev libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev
  libkrb5-dev liblcms1 liblcms1-dev liblcms2-dev libldap2-dev liblodo3.0
  liblog4cxx10 liblog4cxx10-dev liblua5.1-0 liblz4-1 liblz4-dev liblzma-dev
  libmng-dev libmng2 libnetcdf-dev libnetcdfc++4 libnetcdfc7 libnetcdff5
  libodbc1 libogg-dev libogre-1.8-dev libogre-1.8.0 libois-1.3.0
  libopencv-calib3d-dev libopencv-contrib-dev libopencv-core-dev libopencv-dev
  libopencv-features2d-dev libopencv-flann-dev libopencv-gpu-dev
  libopencv-gpu2.4 libopencv-highgui-dev libopencv-imgproc-dev
  libopencv-legacy-dev libopencv-ml-dev libopencv-objdetect-dev
  libopencv-ocl-dev libopencv-ocl2.4 libopencv-photo-dev libopencv-photo2.4
  libopencv-stitching-dev libopencv-stitching2.4 libopencv-superres-dev
  libopencv-superres2.4 libopencv-ts-dev libopencv-ts2.4 libopencv-video-dev
  libopencv-videostab-dev libopencv-videostab2.4 libopencv2.4-java
  libopencv2.4-jni libopenexr-dev libopenmpi-dev libopenmpi1.6 libopenni-dev
  libopenni-sensor-pointclouds0 libopenni0 libp11-kit-dev libpango1.0-dev
  libpci-dev libpcl-1.7-all libpcl-1.7-all-dev libpcl-1.7-bin libpcl-1.7-doc
  libpcl-apps-1.7 libpcl-apps-1.7-dev libpcl-common-1.7 libpcl-common-1.7-dev
  libpcl-features-1.7 libpcl-features-1.7-dev libpcl-filters-1.7
  libpcl-filters-1.7-dev libpcl-geometry-1.7-dev libpcl-io-1.7
  libpcl-io-1.7-dev libpcl-kdtree-1.7 libpcl-kdtree-1.7-dev
  libpcl-keypoints-1.7 libpcl-keypoints-1.7-dev libpcl-octree-1.7
  libpcl-octree-1.7-dev libpcl-outofcore-1.7 libpcl-outofcore-1.7-dev
  libpcl-people-1.7 libpcl-people-1.7-dev libpcl-recognition-1.7
  libpcl-recognition-1.7-dev libpcl-registration-1.7
  libpcl-registration-1.7-dev libpcl-sample-consensus-1.7
  libpcl-sample-consensus-1.7-dev libpcl-search-1.7 libpcl-search-1.7-dev
  libpcl-segmentation-1.7 libpcl-segmentation-1.7-dev libpcl-surface-1.7
  libpcl-surface-1.7-dev libpcl-tracking-1.7 libpcl-tracking-1.7-dev
  libpcl-visualization-1.7 libpcl-visualization-1.7-dev libpcre3-dev
  libpcrecpp0 libphonon4 libpixman-1-dev libplayerc++3.0 libplayerc3.0
  libplayercommon3.0 libplayercore3.0 libplayerdrivers3.0
  libplayerinterface3.0 libplayerjpeg3.0 libplayertcp3.0 libplayerwkb3.0
  libpmap3.0 libpoco-dev libpococrypto9 libpocodata9 libpocofoundation9
  libpocomysql9 libpoconet9 libpoconetssl9 libpocoodbc9 libpocosqlite9
  libpocoutil9 libpocoxml9 libpocozip9 libprotobuf-dev libprotobuf-lite8
  libprotoc8 libpyside-dev libpyside-py3-1.2 libpyside1.2 libqhull-dev
  libqhull6 libqwt-dev libqwt5-qt4 libqwt6 libraw1394-dev libraw1394-tools
  librtmp-dev libsctp-dev libsctp1 libsdformat-dev libsdformat1
  libsdl1.2debian libshiboken-dev libshiboken-py3-1.2 libshiboken1.2 libsilly
  libstatgrab9 libswscale-dev libtar0 libtasn1-6-dev libtbb-dev libtheora-dev
  libtiff5-dev libtiffxx5 libtinyxml-dev libtinyxml2.6.2 libtorque2
  liburdfdom-dev liburdfdom-headers-dev liburdfdom-model-state0.2
  liburdfdom-model0.2 liburdfdom-sensor0.2 liburdfdom-tools
  liburdfdom-world0.2 liburiparser1 libusb-1.0-0-dev libusb-1.0-doc
  libvtk-java libvtk5-dev libvtk5-qt4-dev libvtk5.8 libvtk5.8-qt4 libxaw7-dev
  libxcb-shm0-dev libxcomposite-dev libxcursor-dev libxerces-c3.1 libxi-dev
  libxinerama-dev libxml2-dev libxml2-utils libxmu-dev libxmu-headers
  libxpm-dev libxrandr-dev libyaml-cpp-dev libyaml-cpp0.5 libzzip-0-13
  libzzip-dev lksctp-tools mpi-default-bin mpi-default-dev opencv-data
  openmpi-bin openmpi-common openni-utils phonon phonon-backend-gstreamer
  phonon-backend-gstreamer-common phonon-backend-gstreamer1.0 python-empy
  python-matplotlib python-matplotlib-data python-netifaces python-opencv
  python-opengl python-psutil python-pydot python-pyside python-pyside.phonon
  python-pyside.qtcore python-pyside.qtdeclarative python-pyside.qtgui
  python-pyside.qthelp python-pyside.qtnetwork python-pyside.qtopengl
  python-pyside.qtscript python-pyside.qtsql python-pyside.qtsvg
  python-pyside.qttest python-pyside.qtuitools python-pyside.qtwebkit
  python-pyside.qtxml python-qt4-dev python-qt4-gl python-qwt5-qt4
  python-rosdep python-rospkg python-sip-dev python-support python-tz
  python-urlgrabber python-vtk python-wxtools robot-player
  ros-indigo-actionlib ros-indigo-actionlib-msgs
  ros-indigo-actionlib-tutorials ros-indigo-angles ros-indigo-bond
  ros-indigo-bond-core ros-indigo-bondcpp ros-indigo-bondpy
  ros-indigo-camera-calibration ros-indigo-camera-calibration-parsers
  ros-indigo-camera-info-manager ros-indigo-catkin ros-indigo-class-loader
  ros-indigo-cmake-modules ros-indigo-collada-parser ros-indigo-collada-urdf
  ros-indigo-common-msgs ros-indigo-common-tutorials
  ros-indigo-compressed-depth-image-transport
  ros-indigo-compressed-image-transport ros-indigo-control-msgs
  ros-indigo-cpp-common ros-indigo-cv-bridge ros-indigo-depth-image-proc
  ros-indigo-desktop ros-indigo-diagnostic-aggregator
  ros-indigo-diagnostic-analysis ros-indigo-diagnostic-common-diagnostics
  ros-indigo-diagnostic-msgs ros-indigo-diagnostic-updater
  ros-indigo-diagnostics ros-indigo-driver-base ros-indigo-dynamic-reconfigure
  ros-indigo-eigen-conversions ros-indigo-eigen-stl-containers
  ros-indigo-executive-smach ros-indigo-filters ros-indigo-gazebo-msgs
  ros-indigo-gencpp ros-indigo-genlisp ros-indigo-genmsg ros-indigo-genpy
  ros-indigo-geometric-shapes ros-indigo-geometry ros-indigo-geometry-msgs
  ros-indigo-geometry-tutorials ros-indigo-gl-dependency
  ros-indigo-image-common ros-indigo-image-geometry ros-indigo-image-pipeline
  ros-indigo-image-proc ros-indigo-image-publisher ros-indigo-image-rotate
  ros-indigo-image-transport ros-indigo-image-transport-plugins
  ros-indigo-image-view ros-indigo-interactive-marker-tutorials
  ros-indigo-interactive-markers ros-indigo-joint-state-publisher
  ros-indigo-kdl-conversions ros-indigo-kdl-parser ros-indigo-laser-assembler
  ros-indigo-laser-filters ros-indigo-laser-geometry ros-indigo-laser-pipeline
  ros-indigo-librviz-tutorial ros-indigo-map-msgs ros-indigo-media-export
  ros-indigo-message-filters ros-indigo-message-generation
  ros-indigo-message-runtime ros-indigo-mk ros-indigo-nav-msgs
  ros-indigo-nodelet ros-indigo-nodelet-core ros-indigo-nodelet-topic-tools
  ros-indigo-nodelet-tutorial-math ros-indigo-octomap ros-indigo-orocos-kdl
  ros-indigo-pcl-conversions ros-indigo-pcl-msgs ros-indigo-pcl-ros
  ros-indigo-perception ros-indigo-perception-pcl ros-indigo-pluginlib
  ros-indigo-pluginlib-tutorials ros-indigo-pointcloud-to-laserscan
  ros-indigo-polled-camera ros-indigo-python-orocos-kdl
  ros-indigo-python-qt-binding ros-indigo-qt-dotgraph ros-indigo-qt-gui
  ros-indigo-qt-gui-cpp ros-indigo-qt-gui-py-common ros-indigo-qwt-dependency
  ros-indigo-random-numbers ros-indigo-resource-retriever ros-indigo-robot
  ros-indigo-robot-model ros-indigo-robot-state-publisher ros-indigo-ros
  ros-indigo-ros-base ros-indigo-ros-comm ros-indigo-ros-core
  ros-indigo-ros-tutorials ros-indigo-rosbag ros-indigo-rosbag-migration-rule
  ros-indigo-rosbag-storage ros-indigo-rosbash ros-indigo-rosboost-cfg
  ros-indigo-rosbuild ros-indigo-rosclean ros-indigo-rosconsole
  ros-indigo-rosconsole-bridge ros-indigo-roscpp ros-indigo-roscpp-core
  ros-indigo-roscpp-serialization ros-indigo-roscpp-traits
  ros-indigo-roscpp-tutorials ros-indigo-roscreate ros-indigo-rosgraph
  ros-indigo-rosgraph-msgs ros-indigo-roslang ros-indigo-roslaunch
  ros-indigo-roslib ros-indigo-roslint ros-indigo-roslisp ros-indigo-roslz4
  ros-indigo-rosmake ros-indigo-rosmaster ros-indigo-rosmsg ros-indigo-rosnode
  ros-indigo-rosout ros-indigo-rospack ros-indigo-rosparam ros-indigo-rospy
  ros-indigo-rospy-tutorials ros-indigo-rosservice ros-indigo-rostest
  ros-indigo-rostime ros-indigo-rostopic ros-indigo-rosunit ros-indigo-roswtf
  ros-indigo-rqt-action ros-indigo-rqt-bag ros-indigo-rqt-bag-plugins
  ros-indigo-rqt-common-plugins ros-indigo-rqt-console ros-indigo-rqt-dep
  ros-indigo-rqt-graph ros-indigo-rqt-gui ros-indigo-rqt-gui-cpp
  ros-indigo-rqt-gui-py ros-indigo-rqt-image-view ros-indigo-rqt-launch
  ros-indigo-rqt-logger-level ros-indigo-rqt-moveit ros-indigo-rqt-msg
  ros-indigo-rqt-nav-view ros-indigo-rqt-plot ros-indigo-rqt-pose-view
  ros-indigo-rqt-publisher ros-indigo-rqt-py-common ros-indigo-rqt-py-console
  ros-indigo-rqt-reconfigure ros-indigo-rqt-robot-dashboard
  ros-indigo-rqt-robot-monitor ros-indigo-rqt-robot-plugins
  ros-indigo-rqt-robot-steering ros-indigo-rqt-runtime-monitor
  ros-indigo-rqt-rviz ros-indigo-rqt-service-caller ros-indigo-rqt-shell
  ros-indigo-rqt-srv ros-indigo-rqt-tf-tree ros-indigo-rqt-top
  ros-indigo-rqt-topic ros-indigo-rqt-web ros-indigo-rviz
  ros-indigo-rviz-plugin-tutorials ros-indigo-rviz-python-tutorial
  ros-indigo-self-test ros-indigo-sensor-msgs ros-indigo-shape-msgs
  ros-indigo-smach ros-indigo-smach-msgs ros-indigo-smach-ros
  ros-indigo-smclib ros-indigo-stage ros-indigo-stage-ros ros-indigo-std-msgs
  ros-indigo-std-srvs ros-indigo-stereo-image-proc ros-indigo-stereo-msgs
  ros-indigo-tf ros-indigo-tf-conversions ros-indigo-tf2
  ros-indigo-tf2-geometry-msgs ros-indigo-tf2-kdl ros-indigo-tf2-msgs
  ros-indigo-tf2-py ros-indigo-tf2-ros ros-indigo-tf2-sensor-msgs
  ros-indigo-theora-image-transport ros-indigo-topic-tools
  ros-indigo-trajectory-msgs ros-indigo-turtle-actionlib ros-indigo-turtle-tf
  ros-indigo-turtle-tf2 ros-indigo-turtlesim ros-indigo-urdf
  ros-indigo-urdf-parser-plugin ros-indigo-urdf-tutorial
  ros-indigo-vision-opencv ros-indigo-visualization-marker-tutorials
  ros-indigo-visualization-msgs ros-indigo-visualization-tutorials
  ros-indigo-viz ros-indigo-webkit-dependency ros-indigo-xacro
  ros-indigo-xmlrpcpp sbcl shiboken sip-dev tango-icon-theme tcl-vtk
  ttf-dejavu-core uuid-dev x11proto-composite-dev x11proto-randr-dev
  x11proto-xinerama-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 298 not upgraded.
Installing Python packages...
The directory '/home/bryanz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bryanz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/home/bryanz/.local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/bryanz/.local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: pip in ./.local/lib/python2.7/site-packages (10.0.1)
The directory '/home/bryanz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bryanz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: Latlon in /usr/local/lib/python2.7/dist-packages (1.0.2)
Requirement already satisfied: shapely in /usr/local/lib/python2.7/dist-packages (1.6.4.post1)
Requirement already satisfied: pyproj in /usr/local/lib/python2.7/dist-packages (1.9.5.1)
Requirement already satisfied: pynmea2 in /usr/local/lib/python2.7/dist-packages (1.12.0)
Requirement already satisfied: spidev in /usr/local/lib/python2.7/dist-packages (3.2)
Requirement already satisfied: tornado in ./.local/lib/python2.7/site-packages (4.1)
Requirement already satisfied: pi_ina219 in /usr/local/lib/python2.7/dist-packages (1.1.0)
Requirement already satisfied: certifi in ./.local/lib/python2.7/site-packages (from tornado) (2018.4.16)
Requirement already satisfied: backports.ssl-match-hostname in ./.local/lib/python2.7/site-packages (from tornado) (3.5.0.1)
Requirement already satisfied: mock in /usr/local/lib/python2.7/dist-packages (from pi_ina219) (2.0.0)
Requirement already satisfied: Adafruit-GPIO in /usr/local/lib/python2.7/dist-packages (from pi_ina219) (1.0.3)
Requirement already satisfied: six>=1.9 in ./.local/lib/python2.7/site-packages (from mock->pi_ina219) (1.11.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock->pi_ina219) (1.0.2)
Requirement already satisfied: pbr>=0.11 in ./.local/lib/python2.7/site-packages (from mock->pi_ina219) (4.0.2)
Requirement already satisfied: adafruit-pureio in /usr/local/lib/python2.7/dist-packages (from Adafruit-GPIO->pi_ina219) (0.2.1)
Setting UART frequency...
Setting timezone...
Installing pigpio from apt...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package pigpio
E: Unable to locate package python-pigpio**

Also, @Nanoseb, could you elaborate on what you mean for using the docker image instead of the virtual box? Currently, I have tried launching the ROS simulator nodes from the docker image, which I access within my virtual machine, but the ROS nodes fail. 

Any ideas would be appreciated :)

**Comment by takluyver** [comment]
Looking at that setup script, I think it's maybe only meant to run on the raspberry pi - it installs a number of packages for interfacing with hardware (like pigpio, pi_ina219, i2c_tools, spidev...). We should make that clearer in the naming and/or description.

The whole setup scripts folder probably needs tidying up - there are several scripts that haven't been touched in a couple of years and are probably outdated. And it's not clear what is meant to run where, or in what order.

What failures do you see when you try to launch the simulator in the docker container? Sorry if you already posted this elsewhere - I get a lot of emails and github notifications. :-)

**Comment by tsaoyu** [comment]
@takluyver are you mention [this](https://downloads.ubiquityrobotics.com/pi.html)?

**Comment by takluyver** [comment]
Thanks, that was what I was thinking of. It looks like they also have a VM image, but there are no obvious details on what versions of things it has. https://downloads.ubiquityrobotics.com/vm.html
