### ISSUE TITLE
define sailing_behaviours

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#25]
different sailing behaviours need to be defined, that make sense with smach

- [ ] what behaviours (states) make sense? (keep position, move at speed, race, ???)
- [ ] how is it best integrated with ROS smach?

**Comment by smaria** [comment]
I assume this is outdated (hopefully we will get an update on this by Thursday though)

**Comment by takluyver** [comment]
Yup, this is outdated; I think it's roughly describing what the tasks system does (incidentally, I've written a [wiki page](https://github.com/Maritime-Robotics-Student-Society/sailing-robot/wiki/Tasks-framework) to try to explain tasks).
