### ISSUE TITLE
Get i2c and gpio work with ROS indigo on raspberry pi

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#37]
At the moment most of our sensors are attached via arduino. In the long term, with more and more sensors, it would be cleaner to move as much as possible from the arduinos to the raspberry pi.

We can either have ubuntu and trouble with getting GPIO running, or raspian and troubles with getting an up to date version of ROS.

**Comment by NanaOKA** [comment]
Got the IMU working via i2c with Raspbian Jessie on the Raspberry Pi
