### ISSUE TITLE
Make considerations for the future of the computation board

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#39]
With each board option, there are positives and negatives. We need to figure out what is important to us, and which board is thus the best option for us.

Needs:
- ROS
- python GPIO library

Other Considerations:
- Cost
- popularity
- available documentation

Options:
- BBB
- raspberryPi
- Odroid

Tickets looking at details on this:
#38 
#37

**Comment by NanaOKA** [comment]
Discussed in our last meeting (9th March 2016) and decided to go with the Raspberry Pi with either Ubuntu or Raspbian based on cost, popularity, ROS, Wifi, and i2c
