### ISSUE TITLE
Provide ROS VM

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#4]
For a quick start, a VM with ROS installed makes life for new team members easier.

**Comment by tsaoyu** [comment]
We have published a Wiki page about setup virtual machine on your Windows/Mac computer. Check the page at [wiki](https://github.com/Maritime-Robotics-Student-Society/sailing-robot/wiki/Virtual-Machine-for-Windows-Mac-users).
