### ISSUE TITLE
merge all packages together

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#42]
there is no need to have the packages split up; lets put them all in a single package boaty_mcboatface

**Comment by smaria** [comment]
Thinking about this one - maybe it is better not to do it, but split into two packets: 

- boaty_mcboatface
- sailing_robot

hardware dependent nodes are in boaty_mcboatface
hardware independent nodes are in sailing_robot

everything from sailing_robot can be used for other sailing robots as well
everything in boaty_mcboatface might be better of rewritten if we get a new boat (and we may want to keep boaty_mcboatface so we can still use the original boat)

**Comment by takluyver** [comment]
On the other hand, if a new boat used logically similar components, we may be able to reuse almost all the code with some changes to parameters. It's hard to know how reusable stuff is until we have two boats to run.

**Comment by smaria** [comment]
Ok, lets go with one package for now and split boats away if needed

**Comment by smaria** [comment]
merge was done and tested, please review, merge

**Comment by tsaoyu** [comment]
Correct the name of package from  `src/sailing_robot/src/high_level -> src/sailing_robot/src/sailing_robot`

**Comment by takluyver** [comment]
Closed by #59
