### ISSUE TITLE
Document how to flash the arduinos

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#43]
What libraries need to be installed?

**Comment by tsaoyu** [comment]
In order to compile the Arduino codes, the `ros_lib`should be copy to the Arduino IDE's library.

Once finish installation and setup of rosserial:
```
  cd <sketchbook>/libraries
  rm -rf ros_lib
  rosrun rosserial_arduino make_libraries.py .
```
will do the rest of job

**Comment by takluyver** [comment]
I think it would be good to make a page on Arduino setup (either a Github wiki page or a Samepage page)

**Comment by tsaoyu** [comment]
Thanks for your advice. I have created a Wiki page on github.
