### ISSUE TITLE
Write node that calculates waypoints based on task, weather

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#52]
Whilst we have the markers, the waypoints to go around the markers need to be defined.
We should get one waypoint per marker, giving us a good route to round the marker
Additionally we might also get some 'forbidden' zones from this node to work with the sailing area system ( #51 )

**Comment by Nanoseb** [comment]
This have been implemented, and is not needed in the current competition rules.
