### ISSUE TITLE
Failure handling: avoid rounding the waypoint from the wrong side

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#57]
Because that would mean we have to go again - and we won't even be able to detect this.
See also: #53, #51

**Comment by takluyver** [comment]
From the rules:

> A mark/buoy is considered reached if at least  one track point is recorded within a radius of 5m around the position of the (virtual) buoy.

So we don't have to round buoys like in traditional sailing.
