### ISSUE TITLE
Add compass calibration script to repo

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#62]
@Nanoseb wrote a compass calibration script in the home directory of the raspi we were using yesterday. That needs to be added to git.

**Comment by tsaoyu** [comment]
Calibration code is now under `utilities` folder. Not sure if we need run this every time, so I didn't put it into our `src` folder.

**Comment by Nanoseb** [comment]
It needs to be run every time a hardware part moves.

**Comment by takluyver** [comment]
It's separate from the ROS stuff, so it makes sense to have it in a separate directory. But so long as it's in the repo and we can find it when we need it, it doesn't really matter where it goes.
