### ISSUE TITLE
Create a 7Gb raspbian image

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#67]
That way with 7G it will fit in every possible 8G card.
(http://softwarebakery.com/shrinking-images-on-linux)

**Comment by Nanoseb** [comment]
The image is done, it is the one we were using on Saturday so it should work just fine.

**Comment by tsaoyu** [comment]
I do need test this image with one of our 8 GB card.

**Comment by Nanoseb** [comment]
yes of course, but I don't know what can go wrong this time. But I may be too optimistic ;)

**Comment by tsaoyu** [comment]
I have tested this image. It works fine.

**Comment by Nanoseb** [comment]
Awesome!
