### ISSUE TITLE
Investigate the sign error/offset 

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/sailing-robot#71]
* Investigate the sign error on rudder command and wind direction
* Investigate the offset issue on wind direction

**Comment by Nanoseb** [comment]
For the offset value on the wind direction, I think it is better to handle it in the calibration script because depending on magnets directions it will add/subtract 180 degree. I'll add that.

**Comment by tsaoyu** [comment]
Now the sign issue have been resolved. 
[![a](http://www.marineinsight.com/wp-content/uploads/2015/01/rudder5.png?ca8925)](http://www.marineinsight.com/wp-content/uploads/2015/01/rudder5.png?ca8925)
Need hardware test to figure out an suitable PID value.

**Comment by Nanoseb** [comment]
If everything is in degree and we are using only P, I think a P of 1 is a good start. The final value will probably be lower than that.

**Comment by smaria** [comment]
please include all things decided/noted here in the wiki, since that is where we will check later!

**Comment by tsaoyu** [comment]
Anti-windup have been implemented in `pid_rudder` node.
