### ISSUE TITLE
Create Team Logo

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#9]
- should include the Maritime Robotics Student Society logo (the robot head that is the Logo of the organisation)
- should work in B/W
- the Logo or a simplified version should work as a very small image as well
- maybe something to represent Southampton (Uni? Outline of the Solent?...)

**Comment by JayanthSree** [comment]
Can you please post the logos that are currently in use?

**Comment by smaria** [comment]
I uploaded them in our presentations folder, png and the original inkscape svg

**Comment by smaria** [comment]
Jayanth made good use of our Maritime Robotics logo for our business cards
