### ISSUE TITLE
create simulation

### ISSUE THREAD

**Issue by smaria** [Maritime-Robotics-Student-Society/sailing-robot#90]
just for documentation that Nanoseb is working on this, replacing sensors and actuators with simulated nodes

**Comment by takluyver** [comment]
:+1:

**Comment by Nanoseb** [comment]
Work in progress ;) see branch simulator

**Comment by Nanoseb** [comment]
We now have a working simulator, it manages to go from waypoint to waypoint.
And I think I spotted 2 issues in our code, see #99 and #98 .
If you want to play with it you can use the launch file called `simulator.launch`.

**Comment by takluyver** [comment]
Awesome, thank you! I will play around with this soon.
