### ISSUE TITLE
Compass wrong when boat heals

### ISSUE THREAD

**Issue by takluyver** [Maritime-Robotics-Student-Society/sailing-robot#92]
Tilting the boat affects the reported heading significantly. We need to take the third dimension into account when calculating the heading from the magnetic field readings.

**Comment by smaria** [comment]
Has the fix for this been sufficiently tested?

**Comment by takluyver** [comment]
Not really, but we have a fix for it in principle. So I'm inclined to close this, and open new issues if our fix doesn't work properly.
