### ISSUE TITLE
Find a 2D visualisation tool for position monitoring

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#97]
This will be useful mainly for the simulator and the playback of rosbags.
For now I have found:

* Mapviz: https://github.com/swri-robotics/mapviz
* Rviz: http://wiki.ros.org/rviz
* 2D_plot_tool: https://github.com/clearpathrobotics/2D_Plot_Tool
* Ardupilot/Qgroundcontrol: http://qgroundcontrol.org/

**Comment by Nanoseb** [comment]
I have added a node to see the boat with rviz.

**Comment by Nanoseb** [comment]
In rviz you just have to select "add", and the topic `/debugging_2D_plot` in the `by topic` list.

In the futur I'll probably add waypoints to the map.

**Comment by smaria** [comment]
I would have thought the ardupilot stuff belongs in here?

**Comment by smaria** [comment]
https://github.com/gareth-cross/rviz_satellite this looks like a useful visualisation for us

**Comment by Nanoseb** [comment]
Oh yes, right, I forgot about them. 
Note that the node used right now publish `visualization_msgs` that can be opened by rviz, mapviz and 2D_plot_tool.

**Comment by Nanoseb** [comment]
Rviz is working pretty well, I am going to document that on the wiki.
